- name: ping remote server
  hosts: web
  become: yes
  tasks:
  - name: insatlling nginxin  the remote server successfully
    ansible.builtin.package:
      name: nginx
      state: present
  - name: stating nginx server
    ansible.builin.service:
      name: nginx
      state: started    